CREATE DATABASE Rental_Manha
GO

USE Rental_Manha
GO

CREATE TABLE empresa (
	idEmpresa INT PRIMARY KEY IDENTITY(1,1),
	nomeEmpresa VARCHAR(50) NOT NULL UNIQUE
);
GO

CREATE TABLE marca (
	idMarca INT PRIMARY KEY IDENTITY(1,1),
	nomeMarca VARCHAR(30) NOT NULL UNIQUE
);
GO

CREATE TABLE modelo (
	idModelo INT PRIMARY KEY IDENTITY(1,1),
	idMarca INT FOREIGN KEY REFERENCES marca(idMarca),
	nomeModelo VARCHAR(30) NOT NULL UNIQUE
);
GO

CREATE TABLE veiculo (
	idVeiculo INT PRIMARY KEY IDENTITY(1,1),
	idModelo INT FOREIGN KEY REFERENCES modelo(idModelo),
	idMarca INT FOREIGN KEY REFERENCES marca(idMarca),
	idEmpresa INT FOREIGN KEY REFERENCES empresa(idEmpresa),
	placaVeiculo CHAR(7) NOT NULL UNIQUE
);
GO

CREATE TABLE cliente (
	idCliente INT PRIMARY KEY IDENTITY(1,1),
	nomeCliente VARCHAR(50) NOT NULL UNIQUE,
	cpfCliente CHAR(11) NOT NULL UNIQUE
);
GO

CREATE TABLE aluguel (
	idAluguel INT PRIMARY KEY IDENTITY(1,1),
	idVeiculo INT FOREIGN KEY REFERENCES veiculo(idVeiculo),
	idCliente INT FOREIGN KEY REFERENCES cliente(idCliente),
	dataAluguel SMALLDATETIME NOT NULL
);
GO

ALTER TABLE aluguel DROP COLUMN dataAluguel

ALTER TABLE aluguel
ADD dataAluguel DATE